# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'POC-Firebase-New' do
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  use_frameworks!

  # Pods for POC-Firebase-New

end
